### ISSUE TITLE
Application error [HEROKUAPP]

### ISSUE THREAD

**Issue by mittwz** [Parassharmaa/auto-twitter-dm#2]
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
https://autodm.herokuapp.com/

**Comment by Parassharmaa** [comment]
This is clock based application and visiting the URL will not show anything. The script run on Heroku after a fixed interval. (5 minutes)
If the script is not working, check your logs of your app and post them here, so that I can help.
